version: "3.9"

services:
  frontend:
    build: ./1_frontend
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./2_backend
    container_name: tres_bbdd
    networks:
      - red2
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: monolito
      DB_USER: postgres
      DB_PASSWORD: 1234
    ports:
      - "3007:3000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: monolito
    networks:
      - red2
    volumes:
      - datos_postgres:/var/lib/postgresql/data

networks:
  red2:
    driver: bridge

volumes:
  datos_postgres:
    driver: local
